entityId: https://example.com

assertionConsumerServices:
  - uri: https://example.com/process-response
    index: 0
    isDefault: true

levelsOfAssurance:
  - LEVEL_2

signatureVerificationCertificates:
  - x509: MIIESzCCAzOgAwIBAgIQWOgpeRnCWtyIxyygsV5AkTANBgkqhkiG9w0BAQsFADBZMQswCQYDVQQGEwJHQjEXMBUGA1UEChMOQ2FiaW5ldCBPZmZpY2UxDDAKBgNVBAsTA0dEUzEjMCEGA1UEAxMaSURBUCBSZWx5aW5nIFBhcnR5IFRlc3QgQ0EwHhcNMTcwNTA4MDAwMDAwWhcNMTgwNTA4MjM1OTU5WjBoMQswCQYDVQQGEwJHQjEOMAwGA1UECBMFV2FsZXMxEDAOBgNVBAcTB1N3YW5zZWExDTALBgNVBAoUBERWTEExDDAKBgNVBAsUA0lFUDEaMBgGA1UEAxMRRFZMQVZETFBQTVNBU2lnbjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDErRn/E8TAFOab0IwfAELlc8UN9Lx9w1SXTkRyahB9z+FrnhYkyOGiIrM2logqbi4gHOpwVX616X7qkaKms+mT/elIGHjPJ2dKvShUW91TrW2llAHRVrI4LYrMn8uan5Ci3gx7LSsCM+T6OZ6d5rQp2QMgzeg+lqTjEmi15Jk3ySyDVHcBvCpz2lBL8k3wKbmdWH/hWZRq9zbAA/TA466ExGr6p0jUGQrKLwcL+647h0F2pX4OipajQSTOSAygXLt+unEETB8ThmWCgjLs5+kt8IavK7WDERBiqpoq+sFkLaycjFAQ64zD+wf2XQezVN3szjwXqWUvPlsVAfFlr/kHAgMBAAGjgf8wgfwwDAYDVR0TAQH/BAIwADBhBgNVHR8EWjBYMFagVKBShlBodHRwOi8vb25zaXRlY3JsLnRydXN0d2lzZS5jb20vQ2FiaW5ldE9mZmljZUlEQVBSZWx5aW5nUGFydHlUZXN0Q0EvTGF0ZXN0Q1JMLmNybDAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFIF2UsnTht2BfyfyqRhhBVM72jYxMB8GA1UdIwQYMBaAFN3k9V0aCg860UgiHk7A+G429sUlMDkGCCsGAQUFBwEBBC0wKzApBggrBgEFBQcwAYYdaHR0cDovL3N0ZC1vY3NwLnRydXN0d2lzZS5jb20wDQYJKoZIhvcNAQELBQADggEBAH5W61Tbre9WPUsK83hB27ZI9rUQA9aHcxYm+7Iz9jv+UPaVf6H5y5YA+BU1KFKGdKSIVuPXxyucgR69E6x5pSDlhg6WuhY1+1FGC6o1plts6CAaMN9XHxihr3RGPFyr3kLs/7dI66gnpGRhQKWHehbQn7ZHpbP6YjUlgE8Esqms2FHhBmkraLhTvT6noaadBeUaJUi80CYXHtM/DPtS8dfpaOzuNpGoas5v4OVi9z/vodttvIGzhcvzdkprqGgPOYR7kipGxtDFxJHao/FJQN2em1vRiVKN3gql7ai+FDlWDc+rT8/9ofwqFBqTEqIqh1Ypm5wALlAWBcRL/eRVHBM=

encryptionCertificate:
  x509: MIIESzCCAzOgAwIBAgIQWOgpeRnCWtyIxyygsV5AkTANBgkqhkiG9w0BAQsFADBZMQswCQYDVQQGEwJHQjEXMBUGA1UEChMOQ2FiaW5ldCBPZmZpY2UxDDAKBgNVBAsTA0dEUzEjMCEGA1UEAxMaSURBUCBSZWx5aW5nIFBhcnR5IFRlc3QgQ0EwHhcNMTcwNTA4MDAwMDAwWhcNMTgwNTA4MjM1OTU5WjBoMQswCQYDVQQGEwJHQjEOMAwGA1UECBMFV2FsZXMxEDAOBgNVBAcTB1N3YW5zZWExDTALBgNVBAoUBERWTEExDDAKBgNVBAsUA0lFUDEaMBgGA1UEAxMRRFZMQVZETFBQTVNBU2lnbjEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDErRn/E8TAFOab0IwfAELlc8UN9Lx9w1SXTkRyahB9z+FrnhYkyOGiIrM2logqbi4gHOpwVX616X7qkaKms+mT/elIGHjPJ2dKvShUW91TrW2llAHRVrI4LYrMn8uan5Ci3gx7LSsCM+T6OZ6d5rQp2QMgzeg+lqTjEmi15Jk3ySyDVHcBvCpz2lBL8k3wKbmdWH/hWZRq9zbAA/TA466ExGr6p0jUGQrKLwcL+647h0F2pX4OipajQSTOSAygXLt+unEETB8ThmWCgjLs5+kt8IavK7WDERBiqpoq+sFkLaycjFAQ64zD+wf2XQezVN3szjwXqWUvPlsVAfFlr/kHAgMBAAGjgf8wgfwwDAYDVR0TAQH/BAIwADBhBgNVHR8EWjBYMFagVKBShlBodHRwOi8vb25zaXRlY3JsLnRydXN0d2lzZS5jb20vQ2FiaW5ldE9mZmljZUlEQVBSZWx5aW5nUGFydHlUZXN0Q0EvTGF0ZXN0Q1JMLmNybDAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0OBBYEFIF2UsnTht2BfyfyqRhhBVM72jYxMB8GA1UdIwQYMBaAFN3k9V0aCg860UgiHk7A+G429sUlMDkGCCsGAQUFBwEBBC0wKzApBggrBgEFBQcwAYYdaHR0cDovL3N0ZC1vY3NwLnRydXN0d2lzZS5jb20wDQYJKoZIhvcNAQELBQADggEBAH5W61Tbre9WPUsK83hB27ZI9rUQA9aHcxYm+7Iz9jv+UPaVf6H5y5YA+BU1KFKGdKSIVuPXxyucgR69E6x5pSDlhg6WuhY1+1FGC6o1plts6CAaMN9XHxihr3RGPFyr3kLs/7dI66gnpGRhQKWHehbQn7ZHpbP6YjUlgE8Esqms2FHhBmkraLhTvT6noaadBeUaJUi80CYXHtM/DPtS8dfpaOzuNpGoas5v4OVi9z/vodttvIGzhcvzdkprqGgPOYR7kipGxtDFxJHao/FJQN2em1vRiVKN3gql7ai+FDlWDc+rT8/9ofwqFBqTEqIqh1Ypm5wALlAWBcRL/eRVHBM=

matchingServiceEntityId: https://example.com/msa

matchingProcess:
  cycle3AttributeName: cycle3attr

serviceHomepage: https://example.com/start
enabled: true

shouldHubSignResponseMessages: true

userAccountCreationAttributes:
  - FIRST_NAME
  - FIRST_NAME_VERIFIED
  - SURNAME
  - SURNAME_VERIFIED
  - DATE_OF_BIRTH
  - DATE_OF_BIRTH_VERIFIED
  - CURRENT_ADDRESS
  - CURRENT_ADDRESS_VERIFIED
  - ADDRESS_HISTORY
  - CYCLE_3

simpleId: example-department-example-service
shouldHubUseLegacySamlStandard: false