entityId: http://stub_idp.acme.org/test-stub-idp-example-department-example-service/SSO/POST

simpleId: test-stub-idp

enabled: true
onboardingTransactionEntityIds:
  - https://example.com

supportedLevelsOfAssurance:
  - LEVEL_1
  - LEVEL_2
onboardingLevelsOfAssurance:
  - LEVEL_1
  - LEVEL_2
useExactComparisonType: false
